### ISSUE TITLE
How do i set the new tab page?

### ISSUE THREAD

**Issue by FormalSnake** [molecule47/cat-firefox#1]
^^^^^

**Comment by molecule47** [comment]
I'm assuming you're on windows, so here it goes:

1) navigate to the firefox installation directory
2) open `defaults\pref` 
3) create a file `autoconfig.js` and paste in the following code:
```
//
pref("general.config.filename", "autoconfig.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);
```
4) in the firefox directory `\Program Files\Mozilla Firefox` and create a file `autoconfig.cfg`
5) paste in the following code:
```
//  
var {classes:Cc,interfaces:Ci,utils:Cu} = Components;  
  
try {  
  Cu.import("resource:///modules/AboutNewTab.jsm");  
  var newTabURL = "PATH";  
  AboutNewTab.newTabURL = newTabURL;  
} catch(e){Cu.reportError(e);} // report errors in the Browser Console  
```
in the place of 'PATH' put the location of your HTML file

and you're done!

**Comment by FormalSnake** [comment]
> I'm assuming you're on windows, so here it goes:
> 
>     1. navigate to the firefox installation directory
> 
>     2. open `defaults\pref`
> 
>     3. create a file `autoconfig.js` and paste in the following code:
> 
> 
> ```
> //
> pref("general.config.filename", "autoconfig.cfg");
> pref("general.config.obscure_value", 0);
> pref("general.config.sandbox_enabled", false);
> ```
> 
>     4. in the firefox directory `\Program Files\Mozilla Firefox` and create a file `autoconfig.cfg`
> 
>     5. paste in the following code:
> 
> 
> ```
> //  
> var {classes:Cc,interfaces:Ci,utils:Cu} = Components;  
>   
> try {  
>   Cu.import("resource:///modules/AboutNewTab.jsm");  
>   var newTabURL = "PATH";  
>   AboutNewTab.newTabURL = newTabURL;  
> } catch(e){Cu.reportError(e);} // report errors in the Browser Console  
> ```
> 
> in the place of 'PATH' put the location of your HTML file
> 
> and you're done!

I am on a mac, but thanks anyway!

**Comment by molecule47** [comment]
Well, that's the only operating system that I'm not familiar with haha, but it shouldn't be too different from Linux.

**Comment by FormalSnake** [comment]
> Well, that's the only operating system that I'm not familiar with haha, but it shouldn't be too different from Linux.

Ok, thanks, the only thing missing is the font tho
